### ISSUE TITLE
Github actions CI?

### ISSUE THREAD

**Issue by xnox** [wolfSSL/wolfProvider#44]
Are you considering to use github actions CI at all?

Normally outside contributions are check with them, and also one can contribute CI examples with it.

**Comment by bandi13** [comment]
We do use some Github Actions on our other repos. Just haven't set up any here. We have several tests running on our internal CI which get triggered on pull requests. It is a tough balancing act, on one hand, we want to have our testing visible to the public to show what we are testing, but we don't want to show what we are testing (or its results) to nefarious actors. Being an encryption library this latter part is something we have to keep in mind.

Outside contributions are always welcome and do get thoroughly tested before merging.
